name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      
      - name: Install pnpm
        run: npm install -g pnpm@8
      
      - name: Check versions
        run: |
          node --version
          pnpm --version
          
      - name: Setup git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Install dependencies
        run: pnpm install
        
      - name: Build project (if exists)
        run: pnpm run build --if-present
        
      - name: Test run (if exists)
        run: |
          timeout 10s pnpm run start --if-present || true
